### ISSUE TITLE
nugridse.se can not read mesa se output files from set1ext

### ISSUE THREAD

**Issue by fherwig** [NuGrid/NuGridPy#46]
these lines in executed in  astrohub 
```
from nugridpy import nugridse as mp
mseM2Z0p01=mp.se('/data/nugrid_apod2/data/set1ext/set1.1/see_wind/M2.00Z1.0e-02/M2.00Z0.010')
```
create this error in python 2:
```
Searching files, please wait.......
Sorry, there is no A vector. This can cause problems for reading abundances. Continue...
Sorry, there is no Z vector. This can cause problems for reading abundances. Continue... 
Sorry, there is no isomeric state vector. Continue...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/nugridpy/h5T.py", line 1074, in run
    self.search_deep_sam()
  File "/usr/local/lib/python2.7/dist-packages/nugridpy/h5T.py", line 1315, in search_deep_sam
    self.h5 = mrT.File(self.filename,'r')
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 266, in __init__
    name = filename_encode(name)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/compat.py", line 42, in fspath
    + path_type.__name__)
TypeError: expected str, bytes or os.PathLike object, not newlist

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/nugridpy/h5T.py", line 365, in run
    preprocTable=ascii_table(self.preprocName,self.filename)
  File "/usr/local/lib/python2.7/dist-packages/nugridpy/ascii_table.py", line 178, in __init__
    self.hattrs,self.data=self._readFile(sldir,filename,sep)
  File "/usr/local/lib/python2.7/dist-packages/nugridpy/ascii_table.py", line 307, in _readFile
    tmp.append(float(data[k][j]))
ValueError: could not convert string to float: None
```

There is a similar error in python  3.

**Comment by fherwig** [comment]
I found that this issue now is true for mppnp output as well in python 2.

**Comment by fherwig** [comment]
@jerichooconnell I add you just in case this has to do with some change you did fixing some "this runs not in python 3" issues ...

These are two different errors, one is python 2 error, which is also there for mppnp output. Then there is additional error that is only for python3 that is that it can not read mesa output files.

Try this in both python 2 and then python 3:
```
from nugridpy import nugridse as mp
mp.set_nugrid_path('/data/nugrid_apod2/')
a=mp.se(mass=15,Z=0.001)
```

We have not officially declared python 2 as abandoned. But I am thinking of doing it.
