### ISSUE TITLE
deep_search in h5T.py

### ISSUE THREAD

**Issue by OClarkson** [NuGrid/NuGridPy#51]
Sam, in h5T.py it looks like you started to try to speed up this portion of h5T.py and stopped. 

I am not even directly importing h5T.py but using nudridse
This is what the error I get looks looks like:

```
**Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/nugridpy/h5T.py", line 1074, in run
    self.search_deep_sam()
  File "/usr/local/lib/python3.5/dist-packages/nugridpy/h5T.py", line 1370, in search_deep_sam
    temp =  self.h5.__getitem__(self.cycle_header+str(self.cycle[0])).__getitem__('SE_DATASET').dtype.__str__().split(',')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'cycle1' doesn't exist)"**
```

In h5T.py there is a function run(). Within it if I use self.search_deep() instead of self.search_deep_sam() this issue seems to be corrected which can handle more than one naming convention it seems. Is there a reason we should be using search_deep_sam?

**Comment by swjones** [comment]
Hey.

I think this is when Luke and I needed to make this faster so that remote
data access was possible. I still can not believe how clunky all this is,
but I don't remember this well enough to fix it right now.
Perhaps the issue is "cycle1" instead of padded with zeros, e.g.
"cycle000001"?

Sam
