### ISSUE TITLE
Capitalization in the README example

### ISSUE THREAD

**Issue by pradyunsg** [NuGrid/NuGridPy#55]
CF: https://github.com/pypa/pip/issues/5342

It seems that the first code snippet in the README -- `from NuGridPy import mesa as ms` is incorrect since the only top-level directory in this package is `nugridpy`.

/cc @theparmis

(Gimme a mention if I'm needed; cheers!)

**Comment by ghost** [comment]
Still there is problem with this:
<pre>
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    from nugridpy import mesa as ms 
  File "/Users/USER/anaconda2/lib/python2.7/site-packages/NuGridpy-0.7.4-py2.7.egg/nugridpy/mesa.py", line 140, in <module>
    from . import ascii_table
  File "/Users/USER/anaconda2/lib/python2.7/site-packages/NuGridpy-0.7.4-py2.7.egg/nugridpy/ascii_table.py", line 47, in <module>
    from .data_plot import *
  File "/Users/USER/anaconda2/lib/python2.7/site-packages/NuGridpy-0.7.4-py2.7.egg/nugridpy/data_plot.py", line 59, in <module>
    from . import astronomy as ast
  File "/Users/USER/anaconda2/lib/python2.7/site-packages/NuGridpy-0.7.4-py2.7.egg/nugridpy/astronomy.py", line 26, in <module>
    radiation_constant = 4*boltzmann_sigma/speed_light
NameError: name 'boltzmann_sigma' is not defined

</pre>

**Comment by fherwig** [comment]
the error in the README.md is fixed, thanks for pointing out. the `'boltzmann_sigma' is not defined` is fixed as well in the latest version and is not be in the version from PyPI, but I will check again
